### ISSUE TITLE
tensorflow 2.5 error！

### ISSUE THREAD

**Issue by wwzh2015** [AIWintermuteAI/aXeleRate#49]
Epoch 1/200
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\axelerate\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\axelerate\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\axelerate\lib\site-packages\tensorflow\python\keras\utils\data_utils.py", line 726, in _run
    with closing(self.executor_fn(_SHARED_SEQUENCES)) as executor:
  File "C:\ProgramData\Anaconda3\envs\axelerate\lib\site-packages\tensorflow\python\keras\utils\data_utils.py", line 705, in pool_fn
    initargs=(seqs, None, get_worker_id_queue()))
  File "C:\ProgramData\Anaconda3\envs\axelerate\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\ProgramData\Anaconda3\envs\axelerate\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "C:\ProgramData\Anaconda3\envs\axelerate\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "C:\ProgramData\Anaconda3\envs\axelerate\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\ProgramData\Anaconda3\envs\axelerate\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\ProgramData\Anaconda3\envs\axelerate\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\ProgramData\Anaconda3\envs\axelerate\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle weakref objects

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\axelerate\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\ProgramData\Anaconda3\envs\axelerate\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

----What's Mean? system is win10.

**Comment by AIWintermuteAI** [comment]
https://github.com/AIWintermuteAI/aXeleRate/issues/33#issuecomment-757458788
I added the supporting OS to README already.
